import { useState } from "react";
import Head from "next/head";
import GetTaxiForm from "../components/get-taxi-form";
import styles from "../styles/Home.module.scss";
import TariffsSection from "../components/tariffs-section";
import GetMobileSection from "../components/get-mobile-section";
import Topbar from "../components/topbar";
import Navbar, { MbNavbar } from "../components/navbar";
import Hero from "../components/hero";

export default function GetTaxi() {
  const [show, setShow] = useState(false);

  const showNavbar = (e) => {
    setShow(true);
  };
  const hideNavbar = (e) => {
    setShow(false);
  };
  return (
    <div className={styles.container}>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Topbar />
      <Navbar onClick={showNavbar} />
      <MbNavbar active={show} onClick={hideNavbar} />
      <Hero />
      <GetTaxiForm />
      <TariffsSection />
      <GetMobileSection />
    </div>
  );
}
