import styles from "../styles/Home.module.scss";
import GetTaxiForm from "../components/get-taxi-form";
import HomeHero from "../components/home-hero.js";
import ServicesSection from "../components/services-section";
import TariffsSection from "../components/tariffs-section";
import GetMobileSection from "../components/get-mobile-section";
import TestimonialsSection from "../components/testimonials-section";
import Navbar from "../components/navbar";
import Head from "next/head";
import fakeData from "../fake_data.json";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHero>
        <Navbar type="static" data={fakeData.navLinks} />
      </HomeHero>
      <GetTaxiForm noHeader fullWidth />
      <ServicesSection />
      <TariffsSection yellowTitle="see our" title="tariffs" />
      <GetMobileSection />
      <TestimonialsSection />
    </div>
  );
}
